import './globals.css'
import { StylesProvider } from './styles-provider'
import { Provider } from 'app/provider'
import { ReactElement } from 'react'
import { PortalHost } from '@rn-primitives/portal';
import NextTopLoader from 'nextjs-toploader'

export const metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
}

export default function RootLayout({
  children,
}: {
  children: ReactElement
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} suppressContentEditableWarning={true}>
        <StylesProvider>
          <NextTopLoader
            color="#e0fe0e"
            initialPosition={0.08}
            crawlSpeed={200}
            height={4}
            crawl={true}
            showSpinner={true}
            easing="ease"
            speed={200}
            shadow="0 0 10px #707f07,0 0 5px #707f07"
            template='<div class="bar" role="bar"><div class="peg"></div></div> 
            <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
            zIndex={1600}
            showAtBottom={false}
          />
          <Provider>{children}</Provider>
          <PortalHost />
        </StylesProvider>
      </body>
    </html>
  )
}
